name: autoball-backend
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  webroot: public
  database: mysql:5.7
  cache: none
  xdebug: false
  config:
    database: mysql
