name: autoball-backend
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  webroot: public
  database: mysql:5.7
  cache: none
  xdebug: false
  config:
    database: mysql
proxy:
  appserver:
    - backend.autoball.lndo.site
  mailhog:
    - mail.autoball.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "discover_client_host=0 client_host=host.docker.internal idekey=PHPSTORM"
